#!/bin/bash -e

ROOT_DIR=`pwd`

cd $ROOT_DIR/kmp/ver-browser/src/jsMain/resources
tmux new-window -n b-js

cd $ROOT_DIR/kmp/ver-browser/src/commonMain/kotlin/ru/kornerr
tmux new-window -n b-kt

echo "Test-2"
