#!/bin/bash -e
SDIR=$(cd "$(dirname "$0")" ; pwd -P)

CLD_DIR=$SDIR/../../cross-language-dialect
DST_DIR=$SDIR/../kmp/ver-browser/src/commonMain/kotlin/ru/kornerr

function replace {
    file=$1
    was=$2
    now=$3
    cmd="sed -i '' 's/$was/$now/g' $file"
    eval "$cmd"
}

FILES=(
  CLDContext.kt
  CLDController.kt
  registerOneliners.kt
)

for file in ${FILES[@]}; do
    echo $file
    # Copy original file
    cp $CLD_DIR/kotlin/$file $DST_DIR
    cd $DST_DIR
    # Correct the package and imports
    replace $file "package org.opengamestudio" "package ru.kornerr\nimport kotlin.js.JsExport"
    # Make entities available in JS
    replace $file "interface" "@JsExport\ninterface"
    replace $file "class" "@JsExport\nclass"
    replace $file "fun registerOne" "@JsExport\nfun registerOne"
done
